name: here you action
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install dependencies
        run: yarn

      - name: AWS IAM
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate build
        run: yarn build

      - name: Deploy
        run: aws s3 cp --recursive --region ap-northeast-2 dist s3://hereyoubuckey
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VITE_NODE_ENV: ${{ secrets.VITE_NODE_ENV }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_GOOGLE_MAP_API: ${{ secrets.VITE_GOOGLE_MAP_API }}
          VITE_GOOGLE_AUTH_CLIENT_ID: ${{ secrets.VITE_GOOGLE_AUTH_CLIENT_ID }}
          VITE_KAKAO_REST_API_KEAY: ${{ secrets.VITE_KAKAO_REST_API_KEAY }}
          VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
